filter:
    excluded_paths:
        - '3rdparty/*'
        - 'js/vendor/*'
        - 'js/build/*'
        - 'l10n/*'
        - 'templates/*'
        - 'img/*'
        - 'css/*'
        - 'bin/*'

imports:
    #- javascript  disabled because of es6 producing tons of errors
    - php
    - javascript

tools:
    external_code_coverage:
        timeout: 600

checks:
    php:
        # not helpful because there is no setting to tweek the threshold
        duplication: false